name: runlog
description: "런닝 + 마라톤"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  geolocator: ^14.0.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  url_launcher: ^6.3.1
  flutter_bloc: ^9.1.1
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0
  table_calendar: ^3.2.0
  intl: ^0.20.2
  http: ^1.4.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/running.png
    - assets/.env